name: "Package: InterfaceApp"

on:
  pull_request:
    paths:
      - '.github/workflows/Package-InterfaceApp.yml'
      - 'Packages/InterfaceApp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Run Package Tests
        run: |
          ./Packages/InterfaceApp/run_unit_tests.command
