name: "Package: AppFramework"

on:
  pull_request:
    paths:
      - '.github/workflows/Package-AppFramework.yml'
      - 'Packages/AppFramework/**'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Run Package Tests
        run: |
          ./Packages/AppFramework/run_unit_tests.command
